apiVersion: rke.jet.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: provider-jet-rke
spec:
  credentials:
    source: Secret
    secretRef:
      name: provider-jet-rke
      namespace: crossplane-system
      key: credentials
