apiVersion: rke.rke.jet.crossplane.io/v1alpha1
kind: Cluster
metadata:
  annotations:
  name: xplane-cluster
spec:
  deletionPolicy: Delete
  forProvider:
    nodes:
      - address: 3.217.133.17
        role:
          - controlplane
          - etcd
          - worker
        sshKeySecretRef:
          key: c_mgmt_key_us_east_1.pem
          name: crossplane-key
          namespace: cluster-wide
        userSecretRef:
          key: crossplane-user
          name: crossplane-key
          namespace: cluster-wide
    sshAgentAuth: true
  providerConfigRef:
    name: provider-jet-rke
  publishConnectionDetailsTo:
    configRef:
      name: vault
    name: xplane-cluster-credentials
